In [30]:
import numpy as np
from sklearn.linear_model import OrthogonalMatchingPursuit, Lasso

x=np.array([[1,8,-3,5,4,-9,4],[1,-2,4,8,-2,-3,2],[1,9,6,-7,4,-5,-5],[1,6,-14,-5,-3,9,-2],[1,-2,11,-6,3,-5,1]])
y=np.array([[-32.21],[6.10],[-37.62],[-36.60],[16.75]])

clf = Lasso(alpha=0.5)
clf.fit(x,y)

print('The regularization coefficients from Lasso regression are: \n' + str(clf.coef_))

index=[]
for i in range(len(clf.coef_)):
    if clf.coef_[i] != 0:
        index.append(True)
    else:
        index.append(False)
x_l = x[:,index]
print('The new regularized X = \n' + str(x_l))

print('---------------------------')
omp = OrthogonalMatchingPursuit().fit(x_l, y)
coef = omp.coef_

print('The coefficients of the OMP sparse model are:')
for i in range(len(coef)):
    print('X{} = {}'.format(i,coef[i]))

The regularization coefficients from Lasso regression are: 
[ 0.         -3.80655974  0.70461999 -0.44437137  0.         -0.
  1.41422802]
The new regularized X = 
[[  8  -3   5   4]
 [ -2   4   8   2]
 [  9   6  -7  -5]
 [  6 -14  -5  -2]
 [ -2  11  -6   1]]
---------------------------
The coefficients of the OMP sparse model are:
X0 = -4.657157534246576
X1 = 0.0
X2 = 0.0
X3 = 0.0


In [31]:
print('Q2)')

def grad_desc(gamma):
    # dfdx (found by hand)
    dfdx = lambda x,y: 2*x-2*y-10
    # dfdy (found by hand)
    dfdy = lambda x,y: 2*y-2*x+4

    x_0 = 0
    y_0 = 2
    i = 0
    i_max = 10
    print('For gamma = {}'.format(gamma))
    print('Starting values of x and y:  \t x_0 = {}    y_0 = {}'.format(x_0,y_0))
    while i < i_max:
        x_prev = x_0
        y_prev = y_0
        x_0 = x_0 - gamma*dfdx(x_prev,y_prev)
        y_0 = y_0 - gamma*dfdy(y_prev,y_prev)

        i += 1
        if i > i_max:
            break

        # print('After iteration {}, the values of x and y are: \n'.format(i)) 
        print('For iteration = {}: \t\t x_{} = {}    y_{} = {}'.format(i,i,x_0,i,y_0))

grad_desc(0.05)
print('---------------------------')
grad_desc(0.5)

Q2)
For gamma = 0.05
Starting values of x and y:  	 x_0 = 0    y_0 = 2
For iteration = 1: 		 x_1 = 0.7000000000000001    y_1 = 1.8
For iteration = 2: 		 x_2 = 1.31    y_2 = 1.6
For iteration = 3: 		 x_3 = 1.839    y_3 = 1.4000000000000001
For iteration = 4: 		 x_4 = 2.2951    y_4 = 1.2000000000000002
For iteration = 5: 		 x_5 = 2.6855900000000004    y_5 = 1.0000000000000002
For iteration = 6: 		 x_6 = 3.0170310000000002    y_6 = 0.8000000000000003
For iteration = 7: 		 x_7 = 3.2953279    y_7 = 0.6000000000000003
For iteration = 8: 		 x_8 = 3.5257951100000002    y_8 = 0.4000000000000003
For iteration = 9: 		 x_9 = 3.713215599    y_9 = 0.2000000000000003
For iteration = 10: 		 x_10 = 3.8618940391    y_10 = 2.7755575615628914e-16
---------------------------
For gamma = 0.5
Starting values of x and y:  	 x_0 = 0    y_0 = 2
For iteration = 1: 		 x_1 = 7.0    y_1 = 0.0
For iteration = 2: 		 x_2 = 5.0    y_2 = -2.0
For iteration = 3: 		 x_3 = 3.0    y_3 = -4.0
For iteration = 4: 		 x_4 = 1.0 

In [37]:
print('Q3)')
from sklearn.decomposition import PCA

data = np.genfromtxt('/home/thomas/git/datascience/MSDataSci/506/data/A.csv', delimiter = ',')

n = .70
pca = PCA(n)

pca.fit(data)
print('Using an n of {}, we are returned {} dimensions from PCA'.format(n,pca.n_components_))
print('with an explained variance of {}'.format(pca.explained_variance_))
print('and singular values of {}'.format(pca.singular_values_))
print('---------------------------')

# print(pca.__dict__)

Q3)
Using an n of 0.7, we are returned 2 dimensions from PCA
with an explained variance of [7.77297941 3.7431148 ]
---------------------------
