# Data 506
## Assignment #3

### Q1)
#### a)

In [41]:
#import needed libraries
import numpy as np
from sklearn.linear_model import LinearRegression

# load the data file
data = np.genfromtxt('./D3.csv', delimiter = ',')

In [42]:
# parse the data
X = data[:,0]
Y = data[:,3]

# calculate necessary values for linear regression
avg_x = np.mean(X)
avg_y = np.mean(Y)

x_c = X - avg_x
y_c = Y - avg_y

# calculate the slope and intercept
slope = np.dot(x_c,y_c)/np.dot(x_c,x_c)
intercept = avg_y - (slope * avg_x)

# apply the model to a new dataset
new_x = np.array([0.3, 0.5, 0.8])
pred_y = slope*new_x + intercept

In [43]:
# print Q1) a) results
print('The linear model is:')
print('y = {}x + {}'.format(slope,intercept))
print('--------------------------')
print('For the x values:')
print(new_x)
print('The predicted y values are:')
print(pred_y)

The linear model is:
y = 2.0482891375099084x + -0.1611543552570185
--------------------------
For the x values:
[0.3 0.5 0.8]
The predicted y values are:
[0.45333239 0.86299021 1.47747695]


### Q1)
#### b)

In [44]:
# init partitions array and index array
partitions = []
index = np.arange(0,100)
np.random.shuffle(index)

# create partitions off of a shuffled index array
partitions.append(index[0:33])
partitions.append(index[34:66])
partitions.append(index[67:100])

In [45]:
# init arrays to capture the fit coefficients from each partition
poly_fit2_array = []
poly_fit3_array = []
poly_fit4_array = []

# loop through partitions and fit the data
for part in partitions:
    # init the X and Y training and test data
    X_test = [X[i] for i in part]
    Y_test = [Y[i] for i in part]
    X_train = np.delete(X,[i for i in part])
    Y_train = np.delete(Y,[i for i in part])

    # create the polynomial fits
    poly_fit_2 = np.polyfit(X_train,Y_train,2)
    poly_fit_3 = np.polyfit(X_train,Y_train,3)
    poly_fit_4 = np.polyfit(X_train,Y_train,4)

    # append the polynomial fit coefficients to the array for later
    poly_fit2_array.append(poly_fit_2)
    poly_fit3_array.append(poly_fit_3)
    poly_fit4_array.append(poly_fit_4)

# average the results for each order polynomial fit
poly_fit_2_avg = np.mean(poly_fit2_array, axis=0)
poly_fit_3_avg = np.mean(poly_fit3_array, axis=0)
poly_fit_4_avg = np.mean(poly_fit4_array, axis=0)

In [46]:
# print the polynomial fit results
print('Using 33% holdouts with 3 folds')
print('--------------------------')
print('The total folds average of the coefficients for a 2nd order polynomial are (beginning with the highest order):')
print(poly_fit_2_avg)
print('The total folds average of the coefficients for a 3rd order polynomial are (beginning with the highest order):')
print(poly_fit_3_avg)
print('The total folds average of the coefficients for a 4th order polynomial are (beginning with the highest order):')
print(poly_fit_4_avg)
print('--------------------------')

Using 33% holdouts with 3 folds
--------------------------
The total folds average of the coefficients for a 2nd order polynomial are (beginning with the highest order):
[1.65661662 0.24570062 0.19632911]
The total folds average of the coefficients for a 3rd order polynomial are (beginning with the highest order):
[ 1.39787847 -0.55897894  1.20905763  0.09770094]
The total folds average of the coefficients for a 4th order polynomial are (beginning with the highest order):
[-0.01900558  1.44393518 -0.60448648  1.22960804  0.09467231]
--------------------------


In [47]:
# calculate predicted values with the polynomial models
new_y_2 = poly_fit_2_avg[0]*(new_x**2) + poly_fit_2_avg[1]*new_x + poly_fit_2_avg[2]
new_y_3 = poly_fit_3_avg[0]*(new_x**3) + poly_fit_3_avg[1]*(new_x**2) + poly_fit_3_avg[2]*new_x + poly_fit_3_avg[3]
new_y_4 = poly_fit_4_avg[0]*(new_x**4) + poly_fit_4_avg[1]*(new_x**3) + poly_fit_4_avg[2]*(new_x**2) + poly_fit_4_avg[3]*new_x + poly_fit_4_avg[4]

In [48]:
# print the calculate value results
print('For the x values:')
print(new_x)
print('The predicted y values for a 2nd order polynomial are:')
print(new_y_2)
print('The predicted y values for a 3rd order polynomial are:')
print(new_y_3)
print('The predicted y values for a 4th order polynomial are:')
print(new_y_4)

For the x values:
[0.3 0.5 0.8]
The predicted y values for a 2nd order polynomial are:
[0.41913479 0.73333357 1.45312424]
The predicted y values for a 3rd order polynomial are:
[0.44785284 0.73721983 1.4229143 ]
The predicted y values for a 4th order polynomial are:
[0.44798325 0.73765876 1.42299752]


### Q2)

In [49]:
# create data for testing and training of multiple linear regression
np.random.shuffle(data)

test_data = data[0:20]
train_data = data[21:]

all_x_test_data = test_data[:,0:3]
all_x_train_data = train_data[:,0:3]

y_test_data = test_data[:,3]
y_train_data = train_data[:,3]

In [50]:
# create a multiple linear regression model
model = LinearRegression()
model.fit(all_x_train_data,y_train_data)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [51]:
# print the model results
print('with a single 20% holdout:')
print('r coefficients for the multiple linear model are: \n\tX1 '+str(model.coef_[0])+'\n\tX2 '+str(model.coef_[1])+'\n\tX3 '+str(model.coef_[2]))

test_vals = [0.3, 0.4, 0.1]
Yhat = model.predict([test_vals])
print('--------------------------')
print('For the x values:')
print(test_vals)
print('The predicted y value is:')
print(Yhat)

with a single 20% holdout:
r coefficients for the multiple linear model are: 
	X1 2.300700017696724
	X2 -0.38691790103393103
	X3 0.16862719642004267
--------------------------
For the x values:
[0.3, 0.4, 0.1]
The predicted y value is:
[0.41217549]
